shared_buffers=2GB
effective_cache_size=8GB
work_mem=32MB
maintenance_work_mem=512MB
max_connections=20
max_parallel_workers_per_gather=4
max_parallel_workers=6
wal_compression=on
max_wal_size=4GB
random_page_cost=1.1
